version: "3.5"
services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql-lable
    volumes:
      - /apps/mysql/mydir:/mydir
      - /apps/mysql/datadir:/var/lib/mysql
      - /apps/mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - /apps/mysql/source:/docker-entrypoint-initdb.d
    security_opt:
      - seccomp:unconfined
    environment:
      - "MYSQL_ROOT_PASSWORD=micro.demo.password"
      - "MYSQL_DATABASE=micro_demo"
      - "TZ=Asia/Shanghai"
    networks:
      - etcdnet
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306
  login-service:
    image: login_service:latest
    ports:
      - 50051:50051 # The opening port
    environment:
      MICRO_SERVER_ADDRESS: ":50051" # Specify the Go-micro server port
      PARAMS: "--registry etcd --registry_address etcd:2379"
    networks:
      - etcdnet
    depends_on:
      - etcd # Start after Etcd service start
      - mysql

  login-api-service:
      image: login_api:latest
      ports:
        - 3000:3000
      environment:
        PARAMS: "--registry etcd --registry_address etcd:2379"
      networks:
        - etcdnet
      depends_on:
        - etcd
        - mysql
  etcd:
    hostname: etcd
    image: bitnami/etcd:3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # ports:
    #   - "2379:2379"
    #   - "2380:2380"
    #   - "4001:4001"
    #   - "7001:7001"
    privileged: true
    volumes:
      - "/etcd/data:/opt/bitnami/etcd/data"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - etcdnet

networks:
  etcdnet:
    name: etcdnet